name: Prod workflow # Nom du workflow (affiché dans la console)
on:
  push:
    branches:
      - main # Evenement à partir duquel le WF est lancé
jobs: # Les regroupements d'étapes à appliquer lors du WF
  build-apk-and-release-to-testapp_io:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build release
        run: ./gradlew assembleDebug

      - name: Upload APK TestApp.io
        uses: testappio/github-action@v5
        with:
          api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
          app_id: ${{secrets.TESTAPPIO_APP_ID}}
          file: app/build/outputs/apk/debug/app-debug.apk
          release_notes: ""
          git_release_notes: true
          include_git_commit_id: false
          notify: true